### ISSUE TITLE
Authenticating to Grafana Cloud

### ISSUE THREAD

**Issue by proffalken** [K-Phoen/backstage-plugin-grafana#26]
Hi,

I'm back looking at this again and I'm struggling to get it authenticating with Grafana Cloud.

I have the following configuration:

```
proxy:
  '/grafana/api':
    target: ${GRAFANA_URI}
    headers:
      Authorization: Bearer ${GRAFANA_TOKEN}

grafana:
  # Publicly accessible domain
  domain: ${GRAFANA_URI}
```
and `GRAFANA_URI` is set to `https://<myaccount>.grafana.net/` with `GRAFANA_TOKEN` set to the appropriate value from the grafana.com console.

In the UI, I'm seeing 
![image](https://user-images.githubusercontent.com/262545/159652694-79f0c7d5-065c-4890-9fd7-a6ae4167d96f.png)

but even though `LOG_LEVEL` is set to `debug`, I can't see any debug messages from the plugin in the logs.

Is there a way to enable debug logging via environment variables for this plugin, or another way to troubleshoot it?
