### ISSUE TITLE
Grafana Plugin not finding tags when using Grafana Cloud?

### ISSUE THREAD

**Issue by proffalken** [K-Phoen/backstage-plugin-grafana#27]
Hello, me again! :)

I've been trying to import the alerts from Grafana using the plugin, but for some reason it can't find them when I'm using Grafana Cloud.

I've followed the instructions, and my `catalog-info.yaml` looks like this:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Mventory
  description: The inventory backend for Makerspaces
  annotations:
    grafana/tag-selector: "mventory"
spec:
  type: service
  owner: matt@doics.co
  lifecycle: production
  providesApis:
    - mventory-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mventory-api
  description: The MVentory API
spec:
  type: internal
  lifecycle: production
  owner: matt@doics.co
  definition: "The MVentory API"
```

The challenge I'm having is that in Grafana Cloud it uses the new Grafana Alerts platform and you can't tag an alert, you can only tag a dashboard.

I've tagged the dashboard as appropriate, but the alerts are still not showing up:

![image](https://user-images.githubusercontent.com/262545/160090550-49c6785a-c0c7-4969-af4a-11deb2e3cc53.png)

![image](https://user-images.githubusercontent.com/262545/160090614-eec0b897-4b04-4ebc-8483-3583a5484c81.png)

I'm also struggling to work out how to debug a plugin within Backstage, so I can't really provide you with any relevant log entries because they just come back as the equivalent of "successful, no data was found".
