### ISSUE TITLE
Not finding alerts when querying grafana api

### ISSUE THREAD

**Issue by santinoncs** [K-Phoen/backstage-plugin-grafana#36]
I am seeing in the logs

```
.. backstage info ::1 - - [04/Aug/2022:10:23:04 +0000] "GET /api/proxy/grafana/api/api/alerts?dashboardTag=test-deployment-helm HTTP/1.1" 404 23 "-" "M...
```

but when I query directly it works

```
curl -s  "https://grafana.NNNN/api/alerts?dashboardTag=test-deployment-helm" -H 'Authorization: Bearer xxx' | jq .
[
  {
    "id": 143,
    "dashboardId": 216,
....
  }
]
```

my app-config looks like this

```
  '/grafana/api':
    target: https://grafana.NNNN/
    headers:
      Authorization: Bearer xxx
```

Don't know why..thanks!
