### ISSUE TITLE
Colon in annotation grafana/dashboard-selector not accepted

### ISSUE THREAD

**Issue by marians** [K-Phoen/backstage-plugin-grafana#75]
Found this plugin and gave it a test run. The goal:

On a `Group` entity page, list the dashboards owned by the group.

First I added simple tag selectors like this:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-atlas
  annotations:
    grafana/dashboard-selector: "owner:team-atlas"
```

Result:

    Unexpected ":" at character 5

However this worked:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-atlas
  annotations:
    grafana/dashboard-selector: "tags @> 'owner:team-atlas'"
```
